### ISSUE TITLE
Issue about port and host migration

### ISSUE THREAD

**Issue by YangYoulin** [jacksonrakena/Promul#1]
First, thanks for promul, it's a wonderful relay server.
Really appreciate the hard work.

I'm using promul to develop a multiplayer game with multi rooms.
I used the session to distinguish rooms.
It seems to work well.
**I have a question: are all sessions using the same port?**
Because of some security issue, I can only use one single port for all rooms.
I cannot only distinguish rooms by setting different ports for them.

**And I also have another question: Is it possible to do host migration in promul?**
I have to set host migration for my game in case the host leaves the game.
I just tried to migrate the host at run time by only setting the host to another peer ID "host = peer.Id;" but it made the session disappear and all connections disconnected.
Anyway, how can I do host migration in promul?

**Comment by SyntaxSnafu** [comment]
The relay server only uses one port for all relay traffic which by default I believe is 4098 and the api is 5000, these will be the same for all sessions.

For host migration you will need to create your own solution/change promul for that as it isnt included currently.

**Comment by jacksonrakena** [comment]
Yes, all relay traffic happens over port 4098. There should realistically only be one connection to the relay from a given computer.

Host migration is not something I’m currently investigating. Promul was designed around Unity’s Netcode solution, which does not easily support host migration, as the host usually contains some kind of server-only data that cannot be trivially transferred.

Changing the host identifier, as you suggested, would result in hostbound data packets being sent to a Unity Netcode client that thinks it’s a client (as opposed to the host), which would probably result in it disconnecting, hence the mass disconnections.

If you wanted to look into better support for host migration, I’d appreciate a PR or hearing about anything you’ve investigated.
