### ISSUE TITLE
Unable to build promul project

### ISSUE THREAD

**Issue by seccanj** [jacksonrakena/Promul#2]
Hi and thanks for this project.

I have cloned the repo and trying to build it under Visual Studio, but I'm getting errors complaining that Unity types or namespaces could not be found.

How can I add the needed Unity dependencies to the solution?

Thanks for your support

**Comment by jacksonrakena** [comment]
> Hi and thanks for this project.
> 
> I have cloned the repo and trying to build it under Visual Studio, but I'm getting errors complaining that Unity types or namespaces could not be found.
> 
> How can I add the needed Unity dependencies to the solution?
> 
> Thanks for your support

You should be able to edit `Promul.Runtime.Unity.csproj` ([this file](https://github.com/jacksonrakena/promul/blob/main/src/Promul.Runtime.Unity/Promul.Runtime.Unity.csproj)) lines 15 and 18 to point to the appropriate files in your workspace:  
```xml
<Reference Include="UnityEngine.CoreModule">
  <HintPath>C:\Program Files\Unity\Hub\Editor\2023.1.19f1\Editor\Data\Managed\UnityEngine\UnityEngine.CoreModule.dll</HintPath>
</Reference>
<Reference Include="Unity.Netcode.Runtime">
  <HintPath>D:\Code\Ace In The Hole\Library\ScriptAssemblies\Unity.Netcode.Runtime.dll</HintPath>
</Reference>
```
  
Then all your Unity types and IntelliSense should work as expected.

Ideally, this would be automatic, but I haven't found a way to make it work easily yet.
